name: .NET Core CI

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

#    - name: Test
#      run: dotnet test --no-restore --verbosity normal

    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/GiphyCli.csproj
        
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: GiphyCli
        
        # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        VERSION_STATIC: ${GITHUB_REF:10}

        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false
        
        # Format of the git tag, [*] gets replaced with actual version
        # TAG_FORMAT: v*
        
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
